CREATE TABLE IF NOT EXISTS ${db_schema}.priorities (
    id UUID PRIMARY KEY,
    name_priority VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
